In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(type(arr[1]))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


##### Python List v/s Numpy Array

In [2]:
import numpy as np
import time

# Execution Performance Speed Test
size = 10_000_000

# Python List
py_list = list(range(size))
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()

print(f"Time taken by Python List: {end_time - start_time}")


# Numpy Array
np_list = np.array(py_list)
np_start_time = time.time()
sq_np = np_list**2
np_end_time = time.time()

print(f"Time taken by Python List: {np_end_time - np_start_time}")


Time taken by Python List: 0.6747934818267822
Time taken by Python List: 0.0360105037689209


In [3]:
# Memory Test
import sys

print(f"Python List occupies: {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Python List occupies: {sys.getsizeof(np_list) * len(py_list)} bytes")

Python List occupies: 800000560000000 bytes
Python List occupies: 800001120000000 bytes


In [4]:
'''Numpy Array creation using List'''

arr = np.array((1,2,3,4,5))
print(arr, type(arr), arr.shape)

arr1 = np.array([1,2,3,4,5,"soap"])
print(arr1, type(arr1), arr1.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, type(arr2D), arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'soap'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [5]:
'''Numpy Array creation using built-in methods'''

# Pre filling the 2d array with zeros
arr = np.zeros((2,3), dtype="int64")
print(arr, type(arr), arr.shape, type(arr[1][2]))

# Pre filling the 2d array with 1's
arr1 = np.ones((5, 1), dtype="float32")
print("--------------------------------------------------------------------------------\n", arr1, type(arr1), arr1.shape, type(arr1[2]))

# Prefilling with specific varaible
arr2 = np.full((2,3), 100)
print("--------------------------------------------------------------------------------\n", arr2, type(arr2), arr2.shape)

# Creates identity matrix
arr3 = np.eye(3)
print("--------------------------------------------------------------------------------\n", arr3, type(arr3), arr3.shape)

# Creates array with a range of elements
arr4 = np.arange(0, 11, 2)
print("--------------------------------------------------------------------------------\n", arr4, type(arr4), arr4.shape)

[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> (2, 3) <class 'numpy.int64'>
--------------------------------------------------------------------------------
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]] <class 'numpy.ndarray'> (5, 1) <class 'numpy.ndarray'>
--------------------------------------------------------------------------------
 [[100 100 100]
 [100 100 100]] <class 'numpy.ndarray'> (2, 3)
--------------------------------------------------------------------------------
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'> (3, 3)
--------------------------------------------------------------------------------
 [ 0  2  4  6  8 10] <class 'numpy.ndarray'> (6,)


#### Properties

In [6]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(f"Dimensions (nxm): {arr.shape}")
print(f"Size: {arr.size}")
print(f"Type: {arr.dtype}")
print(f"Dimension (in D): {arr.ndim}")

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

Dimensions (nxm): (3, 3)
Size: 9
Type: int64
Dimension (in D): 2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


### Important Operations

1. Reshaping
2. Indexing (1D and 2D array)
3. Fancy and Boolean Indexing
4. Slicing

In [7]:
# 1. Reshaping

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshape_arr = arr.reshape((3,2))
print(f"\nReshaped arr:\n {reshape_arr, reshape_arr.shape}")

# 2D ==> 1D
flattend_arr = arr.flatten()
print(f"\nFlattend arr:\n {flattend_arr, flattend_arr.shape}")

[[1 2 3]
 [4 5 6]] (2, 3)

Reshaped arr:
 (array([[1, 2],
       [3, 4],
       [5, 6]]), (3, 2))

Flattend arr:
 (array([1, 2, 3, 4, 5, 6]), (6,))


In [8]:
# 2. Indexing

arr = np.array([1,2,3,4,5])
arr2D = np.array([[1,2,3],[4,5,6]])


print(f"Printing elements from 1D array: {arr[2], arr[4]}")
print(f"Printing elements from 2D array: {arr2D[0][1], arr2D[1][2]}")
print(f"Printing elements from 2D array: {arr2D[0:1, 0:2], arr2D[1:2, 1:3]}")



# Fancy indexing
idx = [0,1,2]
print(f"Fancy Indexing: {arr[idx]}")


# Boolean Indexing
print(f"Boolean Indexing: {arr[arr > 3]}")  # %, *, /, etc

Printing elements from 1D array: (np.int64(3), np.int64(5))
Printing elements from 2D array: (np.int64(2), np.int64(6))
Printing elements from 2D array: (array([[1, 2]]), array([[5, 6]]))
Fancy Indexing: [1 2 3]
Boolean Indexing: [4 5]


In [9]:
# 3. Slicing

arr = np.array([1,2,3,4,5])

print(arr[1:4])

[2 3 4]


### Numpy Datatype

1. Integer: **int32, int64**
2. Float: **float32, float64**
3. Boolean: **bool**
4. Complex **Number: complex64, complex128**
5. String: **S {byte-str} & U {unicode-str}**
6. Object: **generic python objects - **object**

#### Multi-Dimensional Array

In [10]:
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D, np.sum(arr2D))


sum_of_columns = np.sum(arr2D, axis=0)
print(f"Sum Of columns (when axis is 0): {sum_of_columns}")

sum_of_rows = np.sum(arr2D, axis=1)
print(f"Sum Of rows (when axis is 1): {sum_of_rows}")

[[1 2 3]
 [4 5 6]] 21
Sum Of columns (when axis is 0): [5 7 9]
Sum Of rows (when axis is 1): [ 6 15]


### Most Used Mathematical Function

* **Aggreation**
1. sum()
2. prod()
3. min()
4. max()
5. mean()
6. std()
7. var()
8. median()
9. argmin()
10. argmax()

* **Power**
1. square()
2. sqrt()
3. pow(a,b)

* **Log & Exponential**
1. log()
2. log10()
3. log2()
4. exp()

* **Rounding**
1. round()
2. floor()
3. ceil()
4. trunc()

* **Extras**
1. unique()
2. sort()
3. abs()